authors:
  zhuwin:
    name: Mizukoud 杼榅
    description: 挂念早已消散的事物，趁其未被遗忘之前。
    avatar: https://weavatar.com/avatar/146cb8c9a0e8deb40912a90dc85cea72e83687a59696a4207dc444e412a9290a?s=256&d=retro&r=pg
    url: https://mizukoud.icu